### ISSUE TITLE
Slides?

### ISSUE THREAD

**Issue by jtemporal** [okaram/spark-pycon15#1]
Hi Orlando! I was [watching your tutorial on youtube](https://www.youtube.com/watch?v=9xYfNznjClE) but I couldn't find your slides anywhere, would you be kind enough to share them?

Thanks! Btw thank you very much for the tutorial, is helping me a lot :)

**Comment by okaram** [comment]
You are able to access the slides, right ?
https://onedrive.live.com/view.aspx?resid=84334A138AC1CCE0!14907&app=PowerPoint

**Comment by jtemporal** [comment]
Yes! Thank you very much @okaram 🎉
